// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4QCkR3zSKgif4CLW8cZufCSOEyrXj22U',
    appId: '1:395916012175:web:80c32c3978381014bd5efa',
    messagingSenderId: '395916012175',
    projectId: 'clearview-23dc5',
    authDomain: 'clearview-23dc5.firebaseapp.com',
    storageBucket: 'clearview-23dc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QCkR3zSKgif4CLW8cZufCSOEyrXj22U',
    appId: '1:395916012175:android:80c32c3978381014bd5efa',
    messagingSenderId: '395916012175',
    projectId: 'clearview-23dc5',
    storageBucket: 'clearview-23dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDugg5vEYG5BKN9Hf8TUUkadVy4-jYz_I',
    appId: '1:395916012175:ios:da1c95da68361b09bd5efa',
    messagingSenderId: '395916012175',
    projectId: 'clearview-23dc5',
    storageBucket: 'clearview-23dc5.firebasestorage.app',
    iosBundleId: 'com.example.clearview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDugg5vEYG5BKN9Hf8TUUkadVy4-jYz_I',
    appId: '1:395916012175:ios:da1c95da68361b09bd5efa',
    messagingSenderId: '395916012175',
    projectId: 'clearview-23dc5',
    storageBucket: 'clearview-23dc5.firebasestorage.app',
    iosBundleId: 'com.example.clearview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4QCkR3zSKgif4CLW8cZufCSOEyrXj22U',
    appId: '1:395916012175:web:80c32c3978381014bd5efa',
    messagingSenderId: '395916012175',
    projectId: 'clearview-23dc5',
    authDomain: 'clearview-23dc5.firebaseapp.com',
    storageBucket: 'clearview-23dc5.firebasestorage.app',
  );
}
